### ISSUE TITLE
Unable to push to repo.

### ISSUE THREAD

**Issue by codeEmitter** [phantomSecrets/phantomSecrets#45]
git@github.com:phantomSecrets/phantomSecrets.git
<img width="943" alt="Screen Shot 2020-06-07 at 1 28 06 PM" src="https://user-images.githubusercontent.com/124598/83975714-2f11b480-a8c3-11ea-839b-15b7edffb041.png">

Any thoughts on this?  It seems I have the right permissions.  Also, would you want to make me an owner here, or member?

Thanks,
Greg

**Comment by codeEmitter** [comment]
<img width="943" alt="Screen Shot 2020-06-07 at 1 34 03 PM" src="https://user-images.githubusercontent.com/124598/83975769-992a5980-a8c3-11ea-877b-344cd3f33c40.png">

**Comment by mattyjones** [comment]
@codeEmitter I will look into this, you are an owner. Is this an SSH issue maybe. I will try and find some logs to sift through in the next day or so.

**Comment by mattyjones** [comment]
@codeEmitter You are all set now. For whatever reason I missed the change in the permission model. Even though you are an owner of the org, I had to grant you explicit rights, you have admin, to do anything with the repo.

**Comment by codeEmitter** [comment]
Thanks!  I couldn’t figure it out.  Used to more simple if I remember.  

I’ll try to keep things on PRs so it’s easier to see changes and what not.  I’m still new to Go, so open to coaching and all.

**Comment by codeEmitter** [comment]
Resolved.
